version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}

  evolution:
    image: atendai/evolution-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=${EVOLUTION_PORT}
      - AUTHENTICATION_API_KEY=${EVOLUTION_AUTHENTICATION_API_KEY}
      - LICENSE_KEY=${EVOLUTION_LICENSE_KEY}
      - QRCODE_LIMIT=${EVOLUTION_QRCODE_LIMIT}
      - WEBHOOK_GLOBAL_ENABLED=${EVOLUTION_WEBHOOK_GLOBAL_ENABLED}
      - WEBHOOK_GLOBAL_URL=${EVOLUTION_WEBHOOK_GLOBAL_URL}
    depends_on:
      - n8n

  server:
    build: .
    restart: always
    environment:
      - PORT=${PORT}
      - EVOLUTION_URL=${EVOLUTION_URL}
      - N8N_URL=${N8N_URL}
    depends_on:
      - n8n
      - evolution
